<div id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
	<table>
		<?php if ($this->getMethod()->getCustomTextForm()){ ?>
		<tr>
			<td><?php echo $this->getMethod()->getCustomTextForm() ?></td>
		</tr>
		<?php } else { ?>
		<tr>
			<td>
			<?php
			//echo $this->__('El pago ser&aacute; realizado en la direcci&oacute;n de destino a traves de ');
			echo $this->getMethod()->getReembolsoDescript() . ".";
			//echo $this->getMethod()->getReembolsoTitle() . ".";
			$data	= $this->getMethod()->getShippMethod();
			echo "<br/><strong>".$this->__('Costo: ');
			echo Mage::helper('checkout')->formatPrice($data['total_shipping'])."</strong>";
			?>
			</td>
		</tr>
		<?php } ?>
	</table>
</div>